### ISSUE TITLE
mediaConnection.answer(_msLocalStream) not working outsite peer.onCall() event

### ISSUE THREAD

**Issue by haunguyen** [nttcom/SkyWay-Android-SDK#4]
When call mediaConnection.answer(_msLocalStream) outsite peer.onCall() event , it's not working. How can I call this method in case sample as click "accept " button when call is comming, not on peer.onCall() event ???

Thank you for your help.

**Comment by tsu-takahashi** [comment]
For example, you can use a DataConnection before calling over a MediaConnection.
An example flow is as follows.

(#A wants to call to #B)
1. #A establishes a DataConnection with #B.
2. #A sends some kind of an indication of call-attempt to #B over the DataConnection.
3. #B alerts the user of #B (pop-up etc), then the user selects "Answer" or "Decline".
4. #B sends the above selection result to #A over the DataConnection.
5. #A calls MediaConnection.call() if the selection of #B(No.3,4) is "Answer".
6. #B calls MediaConnection.answer() in Peer.on(CALL) callback

Best Regards,

**Comment by haunguyen** [comment]
@ tsu-takahashi: Thank for your help.
I got it. So Mediaconnection not include call signaling, only streaming media. Data connection can used to signaling.
