### ISSUE TITLE
Conflict Gson with Retrofit 2

### ISSUE THREAD

**Issue by kainjinez** [nttcom/SkyWay-Android-SDK#9]
I found you used Gson 2.5 for SkyWay. But it was conflict with Retrofit 2 
`compile 'com.squareup.retrofit2:converter-gson:2.1.0'`
This is my error log while compiling
`Error:Execution failed for task ':app:transformClassesWithJarMergingForDebug'. > com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/google/gson/annotations/Expose.class`
How do I solve (or exclude) this?

**Comment by yusuke84** [comment]
@kainjinez 
A similar inquiry was in the past. Sorry for only Japanese.
https://groups.google.com/forum/#!msg/skywayjs/FONoQgVLP04/NdWYtsOLDAAJ

Proposed 1
```
This error could be avoided by unpacking SkyWay.aar, deleting "libs / gson - 2.5.jar", and compressing it again.
```

Proposed 2

```java
// build.gradle

configurations {
    all*.exclude module: 'gson'
}
```

**Comment by kainjinez** [comment]
Thanks. I tried same as your proposed 1 yesterday, and It looks good for now. Thanks

**Comment by tuancoltech** [comment]
Hi kainjinez,

I have the same issue like you.
Could you tell me how exactly did you compress  the lib folder after deleting the gson jar file?
I'm using Windows. 

Thank you

**Comment by kainjinez** [comment]
@tuancoltech Please open aar file with WinRAR, then delete gson-2.5.jar in lbs folder. You don't need to extract it before delete, because WinRAR will extract and compress it automatically.

**Comment by tuancoltech** [comment]
@kainjinez  Thank you very much, it works like a charm.
